### ISSUE TITLE
missing prepend instrumentation leads to `stack level too deep` error

### ISSUE THREAD

**Issue by gsar** [airbrake/airbrake#1161]
it appears that airbrake is using the prepend strategy for instrumentation for most things, however there is [this spot](https://github.com/airbrake/airbrake/blob/dfbd162a6f9f6bdeee7eeb5e7d1449d1770091fb/lib/airbrake/rails/http.rb#L10) that is still using alias method chaining.

this leads to the error when using other gems that use prepend instrumentation such as newrelic. i'm working around the issue [as noted here](https://github.com/newrelic/newrelic-ruby-agent/issues/668#issuecomment-839241641) for now, however, it would be good to see this fixed in the airbrake code base where the problem lies.

**Comment by gsar** [comment]
@kyrylo thanks for the quick resolution! i noticed that these other locations also exist that may need consideration. there are existing [issues](https://github.com/newrelic/newrelic-ruby-agent/issues/656#issuecomment-828630320) in the newrelic repo that are affected by the `resque` conflict. @angelatan2 might be able to provide insight on the others.

![image](https://user-images.githubusercontent.com/6981812/118042368-d6dfff80-b328-11eb-8041-c7ea6942189e.png)

**Comment by kyrylo** [comment]
Thanks for pointing that out. Should be fixed in v11.0.3+

**Comment by owen2345** [comment]
The problem persists in `airbrake-11.0.3` with `newrelic_rpm-7.1.0`

**Comment by gsar** [comment]
@owen2345 i have the same versions as you mentioned and don't see any problems. check your `newrelic.yml` or other config to see if you are forcing method chaining in the newrelic config for some of the methods. it was needed to avoid the issue in older versions and people seem to forget to remove the overrides when they upgrade. the forced config will be in an `instrumentation` block and look like this:

```
  instrumentation:
    httprb: chain
```
