### ISSUE TITLE
Gem fails when not using ActiveRecord in Rails

### ISSUE THREAD

**Issue by lloydpick** [airbrake/airbrake#922]
Hi,

In the newer releases (8.2.*) the code is making an assumption that ActiveRecord is available.

https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails/active_record_subscriber.rb#L42

```
Traceback (most recent call last):
	23: from bin/rails:4:in `<main>'
	22: from bin/rails:4:in `require'
	21: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/commands.rb:17:in `<top (required)>'
	20: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	19: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:67:in `console'
	18: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/commands/commands_tasks.rb:142:in `require_application_and_environment!'
	17: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/application.rb:328:in `require_environment!'
	16: from /Users/lloyd/code/something/config/environment.rb:5:in `<top (required)>'
	15: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/application.rb:352:in `initialize!'
	14: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/initializable.rb:54:in `run_initializers'
	13: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	12: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	11: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	10: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `call'
	 9: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:347:in `each'
	 8: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 7: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 6: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 5: from /Users/lloyd/.rvm/rubies/ruby-2.6.0/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	 4: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/initializable.rb:55:in `block in run_initializers'
	 3: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `run'
	 2: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/railties-4.2.11/lib/rails/initializable.rb:30:in `instance_exec'
	 1: from /Users/lloyd/.rvm/gems/ruby-2.6.0/gems/airbrake-8.2.1/lib/airbrake/rails.rb:10:in `block in <class:Railtie>'
/Users/lloyd/.rvm/gems/ruby-2.6.0/gems/airbrake-8.2.1/lib/airbrake/rails/active_record_subscriber.rb:42:in `<top (required)>': uninitialized constant ActiveRecord (NameError)
```

I'm using Mongoid in this project, and so ActiveRecord has been disabled with commenting out `require active_record/railtie`. So `ActiveRecord` doesn't exist.

**Comment by kyrylo** [comment]
D'oh, of course! Sorry for this mishap :)

**Comment by arekt** [comment]
Similar here, our engine gem doesn't have ActiveRecord dependency. Temporary locked in gemspec to 8.1.4 for now. Waiting for fix :)

**Comment by kyrylo** [comment]
Fixed by https://github.com/airbrake/airbrake/pull/924.

**Comment by arekt** [comment]
Thanks for quick fix but gem is still broken, until new version will be released :)
