### ISSUE TITLE
Airbrake doesn't integrate with Rails when required in initializer

### ISSUE THREAD

**Issue by shaicoleman** [airbrake/airbrake#944]
For my project I need to support multiple error tracking systems depending on environment variables. In environments where Airbrake isn't used, the gem won't be required.

In the Gemfile, I have `gem 'airbrake', require: false`

I've created the following initializer: `config/intializers/0_airbrake.rb`
```
require_relative './filter_parameter_logging'

if Rails.application.config.error_tracker == :airbrake
  require 'airbrake'

  Airbrake.configure do |c|
    c.environment = Rails.env
    c.project_id = Rails.application.secrets.airbrake_project_id
    c.project_key = Rails.application.secrets.airbrake_project_key
    c.blacklist_keys = Rails.application.config.filter_parameters
  end
end
```
With the initializer above, even though it requires `airbrake/rails` it doesn't seem to run the middleware initialization code.

For now, I've found a workaround that involves copying and pasting the code from
https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails.rb
But that's not a maintainable solution

e.g.
```
require_relative './filter_parameter_logging'

if Rails.application.config.error_tracker == :airbrake
  # Initialize https://github.com/airbrake/airbrake/blob/master/lib/airbrake/rails.rb
  require 'airbrake'
  require 'airbrake/rails/action_controller_route_subscriber'
  require 'airbrake/rails/action_controller_notify_subscriber'
  require 'airbrake/rails/action_controller_performance_breakdown_subscriber'
  ActiveSupport::Notifications.subscribe(
    'process_action.action_controller',
    Airbrake::Rails::ActionControllerPerformanceBreakdownSubscriber.new
  )
  require 'airbrake/rails/active_record_subscriber' if defined?(ActiveRecord)

  Rails.application.config.middleware.insert_after(
    ActionDispatch::DebugExceptions,
    Airbrake::Rack::Middleware
  )

  Airbrake.configure do |c|
    c.environment = Rails.env
    c.project_id = Rails.application.secrets.airbrake_project_id
    c.project_key = Rails.application.secrets.airbrake_project_key
    c.blacklist_keys = Rails.application.config.filter_parameters
  end
end
```

**Comment by kyrylo** [comment]
Should be fixed by https://github.com/airbrake/airbrake/pull/942.

**Comment by shaicoleman** [comment]
With version 9.0.0, it's still not integrating with Rails, I need to manually add the middleware, e.g.

```
require_relative './filter_parameter_logging'

if Rails.application.config.error_tracker == :airbrake
  require 'airbrake'
  Rails.application.config.middleware.insert_after(
    ActionDispatch::DebugExceptions,
    Airbrake::Rack::Middleware
  )

  Airbrake.configure do |c|
    c.environment = Rails.env
    c.project_id = Rails.application.secrets.airbrake_project_id
    c.project_key = Rails.application.secrets.airbrake_project_key
    c.blacklist_keys = Rails.application.config.filter_parameters
  end
end
```

**Comment by kyrylo** [comment]
How do other error tracking solutions integrate given this uncommon scenario?

**Comment by shaicoleman** [comment]
I've tried it with Sentry, and it works out of the box, by adding `require 'sentry-raven'`

I believe these are the relevant files:
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/base.rb#L59
https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails.rb

**Comment by kyrylo** [comment]
Thank you!

I have researched this a bit and I believe Sentry doesn't support your setup either (at least not fully). For example, you can use `capture_message` in your controller actions, but when you `require: false` in Gemfile, then this method is undefined and therefore your app will crash in production. It will also not load ActionView and ActiveJob integration code. Maybe it's luck, or maybe you don't use these APIs, that's why your app still works.

They do manage to report exceptions in this mode because they monkey-patch `ActionDispatch::DebugExceptions` in the `config.after_initialize` hook. We, instead, rely on our middleware. We don't report exceptions when you manually require airbrake in your initializer because Rails doesn't load our hooks anymore (and Sentry's hooks as well). When you require airbrake in an initializer, Rails have already loaded all the hooks. I wouldn't want to change the way our railtie works because monkey-patching is the worst possible approach and it's better to use the official API, which has been working well so far. 

I would recommend to pick one service because your app is at risk of crashing (or misbehaving) if you forget about these intricacies. If that's fine, I would recommend to continue using your setup or find a way to require airbrake (and sentry) earlier (before Rails executes the hooks).

**Comment by shaicoleman** [comment]
https://github.com/getsentry/raven-ruby#usage
I've tried both `Raven.capture` and `Raven.capture_exception` and they both work fine.
Errors in the views also get reported.
I'm not using ActiveJob for this app, so haven't been able to test it.

I can understand why you wouldn't want to do a monkey-patch by default, if that's indeed the only way to do it, but I think a reasonable solution would to provide an API that does the monkey-patching but isn't called by default, e.g. Airbrake.inject_rails!

**Comment by kyrylo** [comment]
I didn't test `Raven.capture`, but I was referring specifically to `capture_message` & `capture_exception`: https://github.com/getsentry/raven-ruby/blob/master/lib/raven/integrations/rails/controller_methods.rb

These methods can be accessed from within a controller action. However, with `require: false` they are undefined because [initializers](https://github.com/getsentry/raven-ruby/blob/729c22f9284939695f14822683bff1a0b72502bd/lib/raven/integrations/rails.rb#L13-L15) are not executed when you `require 'sentry-raven'` from within another initializer. [`Raven::Rack`](https://github.com/getsentry/raven-ruby/blob/729c22f9284939695f14822683bff1a0b72502bd/lib/raven/integrations/rails.rb#L9-L11) is not installed either. Therefore, [`Raven::Rack#call`](https://github.com/getsentry/raven-ruby/blob/729c22f9284939695f14822683bff1a0b72502bd/lib/raven/integrations/rack.rb#L43-L67) is not executed either (this is what we use to make Rack integration work).

I am not that familiar with Sentry, but I can see that `Raven::Rack#call` clears context and breadcrumbs. Maybe that is broken as well, I would recommend to check that. I wouldn't want to have a half-broken `Airbrake.load_rails_integration!`.

**Comment by shaicoleman** [comment]
Thanks for taking the time to look into it, I'll leave it up to you whether to close it or look into ways to get it to work.

**Comment by kyrylo** [comment]
Unfortunately, I don't have a good solution here. Changing the way we load the Rails integration is a big task that will require a lot of testing. If this user request was common, it'd be worth looking into that. However, this issue is the first time I've heard anybody wanting this.
